FROM docker.io/bitnami/etcd:3.5
EXPOSE 2379 2380

#CMD ["/usr/local/bin/etcd", "--data-dir=", "data.etcd", "--advertise-client-urls=", "http://etcd-00:2379", "--listen-client-urls=", "http://0.0.0.0:2379", "--initial-advertise-peer-urls=", "http://etcd-00:2380", "--listen-peer-urls=", "http://0.0.0.0:2380", "--initial-cluster=", "etcd-00=http://etcd-00:2380", "--initial-cluster-state=", "new", "--initial-cluster-token=", "etcd-cluster-1"]
