version: '2'

services:
  app:
    build: .
    image: cantakerousmarket:v16
    ports:
      - "9999:9999"
    volumes:
      - db:/app/db
    deploy:
      mode: global
      replicas: 1
volumes:
  db:
